# Generated by Django 3.1.2 on 2020-11-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('extension', models.TextField(null=True)),
                ('size', models.IntegerField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
