# Generated by Django 2.2.7 on 2020-04-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0003_auto_20200408_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('extension', models.TextField(null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.Folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
