# Generated by Django 3.1.2 on 2020-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
