# Generated by Django 3.1.2 on 2020-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_trashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
